= Demo for setting up a Confluent Cloud dedicated cluster with Private Link

This demonstrates how to set up a Confluent Cloud dedicated cluster with Private Link

DISCLAIMER: This project is for demonstration purposes only. Using the demo unmodified in production is highly discouraged. Use at your own risk.

## Precondition

You need the following to run this demo:

* A Confluent Cloud Organization.
* A Confluent Cloud API Key with sufficient access permissions to set up a dedicated cluster and an identity provider including identity pools
* Optionally, this demo can generate a certificate authority (CA) and client certificates in PEM as well as JKS format. For the conversion from PEM to JKS, both `openssl` as well as `keytool` need to be installed and in the PATH.

## Getting started

Set the environment variables 

Then run terraform:

```console
terraform apply
```

You should be able to connect to the database instance following the instructions shown by the terraform output.
The database is pre-initalized with these statements:

```sql
CREATE TABLE IF NOT EXISTS users (
    username TEXT PRIMARY KEY, 
    given_name TEXT, 
    family_name TEXT,
    timestamp TIMESTAMPTZ DEFAULT NOW()
);
INSERT INTO users VALUES('admin', 'Super', 'User', DEFAULT);
INSERT INTO users VALUES('user', 'Regular', 'User', DEFAULT);
```

This makes sure the Kafka connector will find a first table and be able to consume from it.

Add some extra rows:

```sql
INSERT INTO users VALUES('user2', 'Test', 'User', DEFAULT);
INSERT INTO users VALUES('user3', 'Test', 'User', DEFAULT);
```

You can delete (all) rows as usual:

```sql
delete from users;
```

You can create another table with data:

```sql
CREATE TABLE IF NOT EXISTS postaladdress (
    zipcode        VARCHAR(10),
    city           VARCHAR(40),
    street         VARCHAR(40),
    house_number   VARCHAR(10),
    country        VARCHAR(40),
    extra_info     VARCHAR(100) DEFAULT '',
    timestamp      TIMESTAMPTZ DEFAULT NOW(),
    CONSTRAINT user_constraint PRIMARY KEY(zipcode, street, house_number, country)
);
```


```sql
INSERT INTO postaladdress VALUES('08002', 'Barcelona', 'Carrer dels Comtes', '2', 'Catalonia', DEFAULT);
```

== Wrapping things up

You can destroy all created resources including the cluster in Confluent Cloud by running the following command:

```shell
terraform destroy
```
